name: 'Publish'

on:
  push:
    tags:
      - "v*"

jobs:
  compile_natives:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
          
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build --stacktrace
          
      - name: Compress
        shell: bash
        run: |
          cd ./natives/dist
          zip -r ./${{ matrix.zip_name }}.zip *

      - name: Upload
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "./natives/dist/${{ matrix.zip_name }}.zip"
